version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: meu-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: btg_pactual_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

